version: '3'
services:
  web:
    image: valuebound/appserver
    container_name: webapp-${PROJECT_NAME}-${ENV_NAME}
    ports:
      - "8000-8080:80"
      - "3000-3080:443"
    restart: always
    volumes: 
      - ./:/var/www
    depends_on:
      - database
    links:
      - database
  database:
    image: mariadb
    container_name: db-${PROJECT_NAME}-${ENV_NAME}
    ports:
      - "3310-3380:3306"
    volumes:
      - ${DB_VOLUME}:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
